### ISSUE TITLE
Error. Uncaught TypeError: CKEDITOR.document.find(...).toArray is not a function

### ISSUE THREAD

**Issue by koren85** [w8tcha/CKEditor-AutoSave-Plugin#135]
Hi, Thanks for plugin!

I have an error while using the autosave plugin. Autosave doesn't work in Chrome 90.0.4430.85. There is an error in the Chrome DevTools console:

`Uncaught TypeError: CKEDITOR.document.find(...).toArray is not a function`

Code plugins.js:

```
   function loadPlugin(editorInstance, config) {

        GenerateAutoSaveDialog(editorInstance, config, config.SaveKey);

        CheckForAutoSavedContent(editorInstance, config, config.SaveKey, config.NotOlderThen);

        CKEDITOR.tools.array.forEach(CKEDITOR.document.find(config.saveDetectionSelectors).toArray(),
            function(el) {
                el.$.addEventListener("click",
                    function() {
                        RemoveStorage(config.SaveKey, editorInstance);
                    });
            });

        editorInstance.on("change",
            function() {
                startTimer(config, editorInstance);
            });

        editorInstance.on("blur",
            function() {
                startTimer(config, editorInstance);
            });

        editorInstance.on("destroy",
            function() {
                if (config.saveOnDestroy) {
                    SaveData(config.SaveKey, editorInstance, config);
                }
            });
    }
```

Help me please)

**Comment by w8tcha** [comment]
Which version of the editor are you using?

**Comment by koren85** [comment]
CkEditor version 4.16.0

I'm using it in my Redmine plugin from this repository https://github.com/tknrng/redmine_ckeditor

**Comment by w8tcha** [comment]
At least i cannot reproduce the issue with ckeditor 4.16. but i dont use this plugin.

did you have anything setup in the editor config for the autosave plugin?

**Comment by koren85** [comment]
Thanks for your help, I have established that the problem is only observed in the chrome browser. Plugin settings by default, as described. I'll try to reinstall my browser
